language: node_js
node_js: 10
dist: bionic

script: 
  - npm run build
  - echo "Would you like to play a game?"

deploy:
  provider: s3
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  bucket: "metronome.io"
  acl: public_read
  skip_cleanup: true
  region: us-east-2
  local_dir: build
  on:
    branch: master
